export const ADD_JOURNAL = 'ADD_JOURNAL';
export const UPDATE_JOURNAL = 'UPDATE_JOURNAL';
export const DELETE_JOURNALS = 'DELETE JOURNALS';
export const DELETE_JOURNAL = 'DELETE JOURNAL';

export const RECEIVE_JOURNALS = 'RECEIVE_JOURNALS';
export const FETCH_ALL_JOURNALS = 'FETCH_ALL_JOURNALS';