export const ADD_JOURNAL = 'ADD_JOURNAL';
export const UPDATE_JOURNAL = 'UPDATE_JOURNAL';
export const DELETE_JOURNALS = 'DELETE JOURNALS';

export const ADD_ENTRY = 'ADD_ENTRY';

export const RECEIVE_JOURNALS = 'RECEIVE_JOURNALS';
export const FETCH_ALL_JOURNALS = 'FETCH_ALL_JOURNALS';